version: "3.6"

services:
    nginxx:
      build:
        context: ./nginx
      container_name: go_v1_nginx
      volumes:
        - ${APP_CODE_WEB_PATH_HOST}:${APP_CODE_WEB_PATH_CONTAINER}
        - ${NGINX_WEB_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_WEB_SITE_PATH}:/etc/nginx/sites-available/web.conf
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "3636:80"
        - "3637:443"
      depends_on:
        - web
      links:
        - web  
      networks:
        - frontend   

    web:
      build:
        context: ./app
        args:
          - GO_VERSION=${GO_VERSION}
          - INSTALL_NPM=${INSTALL_NPM}
          - INSTALL_CRON=${INSTALL_CRON}
          - INSTALL_GIT=${INSTALL_GIT}
          - INSTALL_ZIP=${INSTALL_ZIP}
          - NODE_VERSION=${NODE_VERSION}      
      container_name: go_v1_web
      volumes:
        - ${APP_CODE_WEB_PATH_HOST}:${APP_CODE_WEB_PATH_CONTAINER}   
      expose:
        - "9000"
      ports:
        - "9000"
      depends_on:
        - db
        - redis
      links:
        - db
        - redis
      networks:
        - frontend
        - backend

    db:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      container_name: go_v1_db
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

    redis:
      build: ./redis
      container_name: go_v1_redis
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - backend          

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  db:
    driver: ${VOLUMES_DRIVER}   
  redis:
    driver: ${VOLUMES_DRIVER} 

